### ISSUE TITLE
Use sesdiff in Python, not as shell command

### ISSUE THREAD

**Issue by pirolen** [proycon/sesdiff#1]
Hi, would there be a way to use sesdiff in a Python script, without having to call it using a subprocess-like module, and having to write data to a file and read that in?

**Comment by proycon** [comment]
Currently not, but I could write a python binding for that if you want. 
It could indeed reduce overhead and make things more performant.

@DirkRoorda: Would such a thing also be interesting for you? You
asked about sesdiff earleir this week and were doing something similar in
Python.

**Comment by pirolen** [comment]
> Currently not, but I could write a python binding for that

That would be great, thanks!

**Comment by dirkroorda** [comment]
That will lower the barrier to actually use it, in my case, sure.

**Comment by proycon** [comment]
A python binding has been implemented now as sesdiff v0.3.1, please see https://github.com/proycon/sesdiff/tree/master/python for instructions!

**Comment by pirolen** [comment]
Thanks a lot!
Printing the result to stdout or redirecting to a file by the print command works fine, but can that be that when I wanted to write the results to a file using pandas write_csv, the result object seems to end up as e.g. `<builtins.EditScript object at 0x7f0ac48ad770>`. How can I write the result string to a file?

Ah, ok, writing the object e.g. as a dict works of course, sorry...

**Comment by proycon** [comment]
Right, good point, I hadn't implemented string serialisation of the entire object, you'd have to do it yourself. I have now implemented it a new version v0.3.2, so you can just do `print(editscript)` and `str(editscript)` and get the expected behaviour.
